<?php

function ajax_time_menu() {
    $items = array();

    $items['ajax-test'] = array(
        'title' => 'Ajax Test',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => "ajax_time_page",
        'access arguments' => array('access content'),
    );
    $items['my-ajax-test/%'] = array(
        'title' => 'Ajax test callback',
        'type' => MENU_CALLBACK,
        'page callback' => 'ajax_time_callback',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
    );
    return $items;
}

function ajax_time_page(){
    return array(
        '#type' => 'link',
        '#title' => t('Ajax Time'),
        '#href' => 'my-ajax-test/nojs',
        '#prefix' => '<div id="ajax-time">',
        '#suffix' => '</div><div id="ajax-display"></div>',
        '#ajax' => array('effect' => 'fade',
            ),
    );
}

function  ajax_time_callback($ajax) {
    $time = t('The current time is : !time', array('!time' => date('Y-m-d H:i:s')));

    if ($ajax == 'ajax') {
        $commands = array();
        $commands[] = ajax_command_replace('#ajax-display', "<div id='ajax-display'>" . $time . "</div>");
        $commands[] = ajax_command_changed('#ajax-display');
        $commands[] = ajax_command_invoke(NULL, "ajax_time");
        ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
    }
    else {
        return array(
            '#markup' => $time,
            );
    }
}
